name: Send alerts cron job
on:
  schedule:
    - cron: 0 7 * * *
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send alerts cron job
        run: |
          curl --request POST \
            --url '${{ vars.NEXT_PUBLIC_FALLBACK_SITE_URL }}/api/send-alerts' \
            --header 'Authorization: Bearer ${{ secrets.CRON_API_KEY }}'
